CXX := g++-12
CXXFLAGS := -O3 -std=c++20 -pthread -g
SRCS := Simulation_RL.cpp \ 
		Simulation_TEMP.cpp \
		Simulation_LFU.cpp \
		Simulation_LFU-OSA.cpp \
		Simulation_LRU.cpp \
		Simulation_LRU-OSA.cpp \
		Simulation_LRFU.cpp \
		Simulation_EXD.cpp \
		Simulation_ideal.cpp \
		Simulation_static.cpp
DEPS := BS_thread_pool.hpp RL_Agent_2states.h

# Extract the base name (without extension) of each source file
EXECS := $(SRCS:.cpp=)

# Rule to compile each source file into an executable
all: $(EXECS)

%: %.cpp $(DEPS)
	$(CXX) $(CXXFLAGS) -o $@ $<
