CXX := g++
CXXFLAGS := -std=c++17 -pthread -g
SRCS := Simulation_static_20hf90_rw1_10000.cpp Simulation_RL_20hf90_rw1_10000.cpp Simulation_RLs1_20hf90_rw1_10000.cpp Simulation_LFU_20hf90_rw1_10000.cpp Simulation_LRU_20hf90_rw1_10000.cpp
DEPS := BS_thread_pool.hpp RL_Agent_2states.h

# Extract the base name (without extension) of each source file
EXECS := $(SRCS:.cpp=)

# Rule to compile each source file into an executable
all: $(EXECS)

%: %.cpp $(DEPS)
	$(CXX) $(CXXFLAGS) -o $@ $<
